import wget
import os
def main():
	print("Le Script se déroullera en environ ~20 Minute (Testé sur un AMD A4 avec une connection 100 Mbps)\n")
	print("Instllation du dépot EPEL de CentOS 7\n")
	os.system("yum install epel-release -y")
	print("Installation de yum-utils\n")
	os.system("yum install yum-utils -y")
	print("Installation de RPMConf\n")
	os.system("yum install rpmconf")
	print("Execution de RPMConf, merci de laissez les choix par défaut !\n")
	os.system("rpmconf -a")
	print("Un peu de ménage\n")
	os.system("package-cleanup --leaves -y")
	os.system("package-cleanup --orphans -y")
	print("Installation de DNF, le remplacent de YUM\n")
	os.system("yum install dnf -y")
	print("Désinstallation de YUM\n")
	os.system("dnf -y remove yum yum-metadata-parser")
	os.system("rm -Rf /etc/yum")
	print("Phase de préparation terminer, démarrage de la mise a niveau vers CentOS 8, merci de ne pas éteindre la machine !\n")
	print("Mise a jours de CentOS 7\n")
	os.system("dnf upgrade -y")
	print("Mise a niveau des dépots vers les dépots de centOS 8\n")
	os.system("dnf install -y https://voxan24.github.io/Linux_Script/ress/centos-gpg-keys-8-2.el8.noarch.rpm")
	os.system("dnf install -y https://voxan24.github.io/Linux_Script/ress/centos-linux-release-8.3-1.2011.el8.noarch.rpm")
	os.system("dnf install -y https://voxan24.github.io/Linux_Script/ress/centos-linux-repos-8-2.el8.noarch.rpm")
	print("Mise a niveau de EPEL\n")
	os.system("dnf -y upgrade https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm")
	print("Encore un peu de ménage\n")
	os.system("dnf clean all")
	print("Désinstallation de l'ancien Kernel de CentOS 7\n")
	os.system("rpm -e `rpm -q kernel`")
	os.system("rpm -e --nodeps sysvinit-tools")
	print("Mise a niveau vers CentOS 8\n")
	os.system('dnf -y --releasever=8 --allowerasing --setopt=deltarpm=false distro-sync')
	os.system("dnf -y install kernel-core")
	os.system('dnf -y groupupdate "Core" "Minimal Install"')
	os.system("cat /etc/redhat-release")
	print("Mise a niveau terminer, merci d'appuyer sur n'importe quel touche et faire entrer pour redemarrer le system\n")
	input()
	os.system("shutdown -r now")